language: scala
sudo: true
jdk:
  - openjdk8
scala:
  - 2.10.4  # should match version in build.sbt
python: "2.6"
install:
  - sudo pip install inspyred
  - sudo pip install argparse
script:
  - sbt clean test

# only build PRs for the following branches (not all branch pushes)
branches:
  only:
    - master
    - tuning_20190221

